#pragma once

// From glfw3.h //

#define CANDLE_MOUSE_BUTTON_1         0
#define CANDLE_MOUSE_BUTTON_2         1
#define CANDLE_MOUSE_BUTTON_3         2
#define CANDLE_MOUSE_BUTTON_4         3
#define CANDLE_MOUSE_BUTTON_5         4
#define CANDLE_MOUSE_BUTTON_6         5
#define CANDLE_MOUSE_BUTTON_7         6
#define CANDLE_MOUSE_BUTTON_8         7
#define CANDLE_MOUSE_BUTTON_LAST      CANDLE_MOUSE_BUTTON_8
#define CANDLE_MOUSE_BUTTON_LEFT      CANDLE_MOUSE_BUTTON_1
#define CANDLE_MOUSE_BUTTON_RIGHT     CANDLE_MOUSE_BUTTON_2
#define CANDLE_MOUSE_BUTTON_MIDDLE    CANDLE_MOUSE_BUTTON_3